# Generated by Django 4.2.3 on 2023-11-03 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_alter_category_options_item'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='image',
            field=models.ImageField(default='/media/Profile_Images/DefaultProfPic.jpg', upload_to='item_images'),
            preserve_default=False,
        ),
    ]
