# Generated by Django 4.2.3 on 2023-11-28 03:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_item_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='ItemImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='item_images')),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_images', to='item.item')),
            ],
        ),
        migrations.AddField(
            model_name='item',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='itemsImages', to='item.itemimage'),
        ),
    ]
